### PR TITLE
Easy-to-Read english version of bible

### PR DESCRIPTION
**Pull request by heni**

### CODE REVIEW

**Comment by bobuk** [comment]
Do you have some plans to add more or ERV it's enough for the start?
What do you think?

**Comment by heni** [comment]
I have semi-parsed NIV ( https://en.wikipedia.org/wiki/New_International_Version ) and RSVCE ( https://en.wikipedia.org/wiki/Revised_Standard_Version_Catholic_Edition ) versions but it will take a time to bring these versions to good condition (for commit)

**Comment by bobuk** [comment]
I have prepared some versions, is that possible to ask you to check it out?
https://yadi.sk/d/s0zzQwW4rpvKQ

**Comment by heni** [comment]
Yeah I can add these versions into this PR

**Comment by bobuk** [comment]
Please do it and I'll merge :)

**Comment by bobuk** [comment]
Ping. @heni are you ok to do it?

**Comment by heni** [comment]
Sorry for long delay!
All done :)

**Comment by heni** [comment]
And unfortunately I haven't understood what bible revision is under BOOKS.json files.
After small examination of content I suppose that it's like a "New International Version".
Is it true? And if yes does make sense to rename BOOKS.json files to NIV.json ones.

**Pull request merged**
